### ISSUE TITLE
can you provide a detailed user guide?

### ISSUE THREAD

**Issue by basicallynewbie** [iojanis/Lity#1]
Lity is exactly what I wanted a node based note program. But I want to get more detail. I only know I can use @ to create a new node after watched the video. Are there any more features not self-explained?

**Comment by iojanis** [comment]
Sorry for the late response; this completely went under my radar.

I've come across some architectural limitations, which led to a rewrite of the entire system. This includes not only Lity but also the backend server. Lity is currently still more of a prototype. Real-time collaboration does work, but I never provided server software. (hocuspocus.dev provides very simple examples.)

I'm still nowhere near finished. This will take more time. At some point, I guess I'll integrate Lity into my new projects. Until then, check out the code; you may find some additional hidden features... 🕵🏻‍♂️
